name: Deploy to custom server

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'backend-nest/**'

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install nest dependencies
      run: |
        cd backend-nest
        npm ci

    - name: Run build
      run: |
        cd backend-nest
        npm run build

    - name: Create .env file
      run: |
        cd backend-nest
        touch .env
        echo "${{ secrets.NODE_PROD_ENV }}" > .env

    - name: Start the application with PM2
      run: |
        cd backend-nest
        npm install pm2 -g
        pm2 status
        pm2 restart ecosystem.config.js
        
    - name: Creating the frontend .env
      run : |
          cd frontend/website
          touch .env
          echo "${{ secrets.FRONTEND }}" > .env
      
    - name: Installing the dependencies
      run : |
        cd frontend/website
        npm ci

    - name: Run build frontend website
      run: |
        cd frontend/website
        npm run build
    
    - name: pm2 for frontend
      run: |
        cd frontend/website
        npm install pm2 -g
        pm2 status
        pm2 restart ecosystem.config.js
